# Generated by Django 4.2.2 on 2023-06-22 15:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimos',
            fields=[
                ('id_client', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpf', models.IntegerField(max_length=15)),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=400)),
                ('valor', models.FloatField()),
                ('status', models.CharField(max_length=50)),
                ('data_solicitado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
