# Generated by Django 4.2.2 on 2023-06-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='cpf',
            field=models.IntegerField(),
        ),
    ]
